DROP DATABASE IF EXISTS onlineShop;
CREATE DATABASE onlineShop;
USE onlineShop;

CREATE TABLE Kunde (
	K_ID int PRIMARY KEY AUTO_INCREMENT,
	K_VORNAME varchar(255),
	K_NACHNAME varchar(255),
	K_EMAIL varchar(255) UNIQUE
);

CREATE TABLE Bestellung (
	B_ID int PRIMARY KEY AUTO_INCREMENT,
	B_DATUM DATETIME,
	B_KID int REFERENCES Kunde(K_ID)
);

CREATE TABLE Produkt(
	P_ID int PRIMARY KEY AUTO_INCREMENT,
	P_NAME varchar(255),
	P_BESCHREIBUNG varchar(255),
	P_PREIS double(10,2)
);

CREATE TABLE PIB (
	PIB_BID int,
	PIB_PID int,
	PIB_PREIS double(10,2),
	PIB_MENGE int,
	PRIMARY KEY (PIB_BID, PIB_PID),
	FOREIGN KEY (PIB_BID) REFERENCES Bestellung(B_ID),
	FOREIGN KEY (PIB_PID) REFERENCES Produkt(P_ID)
);
