loadErrorAlert.contentText=During loading the configuration an error occurred: 
loadErrorAlert.headerText=Load failed
saveErrorAlert.contentText=During saving the configuration an error occurred: 
saveErrorAlert.headerText=Save failed